all:
children:
    backend:
      hosts:
        i-05e5ebaa14f838edb:
           ansible_connection: amazon.aws.aws_ssm
           ansible_user: ubuntu
           ansible_aws_ssm_region: us-east-1
           ansible_aws_ssm_bucket_name: techbleat744
           ansible_region: us-east-1

