plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

keyed_groups:
  - key: tags.Role
    prefix: role

filters:
  tag:Role: backend
  instance-state-name: running

hostnames:
  - instance-id

compose:
  ansible_connection: amazon.aws.aws_ssm
  ansible_aws_ssm_region: us-east-1
  ansible_aws_ssm_bucket_name: techbleat744
  ansible_user: ubuntu
  ansible_remote_tmp: /tmp/.ansible/tmp

