all:
  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
  children:
    backend:
      hosts:
       i-01c05b095d6e56ec8:
           ansible_connection: amazon.aws.aws_ssm
           ansible_user: ubuntu
           ansible_aws_ssm_region: us-east-1
           ansible_aws_ssm_bucket_name: techbleat744
           ansible_region: us-east-1
           ansible_remote_tmp: /tmp/.ansible/tmp

    frontend:
      hosts:
        i-0db4fe2c8bfedec49:
           ansible_connection: amazon.aws.aws_ssm
           ansible_user: ubuntu
           ansible_aws_ssm_region: us-east-1
           ansible_aws_ssm_bucket_name: techbleat744
           ansible_region: us-east-1
           ansible_remote_tmp: /tmp/.ansible/tmp


