app_name: fast-api
app_user: ubuntu
app_dir: /home/ubuntu/class25-26-project2
venv_dir: /home/ubuntu/class25-26-project2/.venv
git_repo: https://github.com/techbleat/class25-26-project2.git
app_port: 8000
app_file: /home/ubuntu/app.py
