---
- name: Install snapd
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Ensure snapd is running
  systemd:
    name: snapd
    state: started
    enabled: yes

- name: Install core snap
  command: snap install core
  args:
    creates: /snap/bin/core

- name: Refresh snap core
  command: snap refresh core

- name: Install Certbot
  command: snap install --classic certbot
  args:
    creates: /snap/bin/certbot

- name: Create symlink for certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
    force: yes

- name: Remove default Nginx config
  file:
    path: /etc/nginx/sites-enabled/fast-api
    state: absent
  notify: Restart Nginx

- name: Create certbot letsencrypt Nginx config in sites available
  template:
    src: reverse-proxy-certbot.j2
    dest: /etc/nginx/sites-available/reverse-proxy-certbot
  notify: Restart Nginx

- name: Enable certbot letsencrypt Nginx config in sites enabled
  file:
    src: /etc/nginx/sites-available/reverse-proxy-certbot
    dest: /etc/nginx/sites-enabled/reverse-proxy-certbot
    state: link
  notify: Restart Nginx

- name: Ensure Nginx is restarted before certbot
  meta: flush_handlers

- name: Obtain SSL certificate with Nginx plugin
  command: >
    certbot --nginx
    -d {{ domain_name }}
    --non-interactive
    --agree-tos
    -m {{ certbot_email }}
    --redirect
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"

  handlers:
  - name: Restart Nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes

