name: Terraform and Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      role_arn: ${{ steps.tf.outputs.role_arn }}

    steps:
      # ----------------------------------
      # Checkout repo
      # ---------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # Setup Terraform
      # ----------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # ----------------------------
      # Terraform Init
      # ----------------------------
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure

      # -----------------------------
      # Terraform Apply
      # ------------------------------
      - name: Terraform Apply
        working-directory: terraform
        run: 
          terraform apply --auto-approve

      - name: Get Terraform Output
        working-directory: terraform
        id: tf
        run: 
          echo "role_arn=$(terraform output -raw github_actions_role_arn)" >> $GITHUB_OUTPUT

      - name: Terraform output to json
        working-directory: terraform
        run: terraform output -json > tf_output.json



  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    permissions:
      id-token: write
      contents: read

    steps:
      # ----------------------------------
      # Checkout repo
      # ---------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
# ----------------------------
      # Install Python 
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Ansible and dependencies
        run: |
            python -m pip install --upgrade pip

      - name: Install Ansible and dependencies2
        run: |
            pip install ansible boto3 botocore 

      - name: Install amazon.aws collection
        run: |
            ansible-galaxy collection install amazon.aws

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: ${{ needs.terraform.outputs.role_arn }}
         aws-region: us-east-1

      - name: Run Ansible Playbook
        run: |
            ansible -i ansible/inventory/inventory_aws_ec2.yml -m ping -vvvvv