name: Terraform and Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      role_arn: ${{ steps.tf.outputs.role_arn }}
      frontend_pub_ip: ${{ steps.tfftpubip.outputs.frontend_pub_ip }}
      backend_pri_ip: ${{ steps.tfbkprip.outputs.backend_pri_ip }}
      frontend_inst_id: ${{ steps.tfftinstid.outputs.frontend_inst_id }}
      backend_inst_id: ${{ steps.tfbkinstid.outputs.backend_inst_id }}
      


    steps:
      # ----------------------------------
      # Checkout repo
      # ----------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # Setup Terraform
      # ----------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # ------------------------------
      # Terraform Init
      # ------------------------------
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure

      # -----------------------------
      # Terraform Apply
      # -------------------------------
      - name: Terraform Apply
        working-directory: terraform
        run: 
          terraform destroy --auto-approve

      - name: Terraform Output for Ansible Variables
        working-directory: terraform
        run: 
          terraform output -json > ../ansible/tf_output.json

      - name: Get Role ARN Output
        working-directory: terraform
        id: tf
        run: 
          echo "role_arn=$(terraform output -raw github_actions_role_arn)" >> $GITHUB_OUTPUT

      - name: Get Terraform Frontend Public IP
        working-directory: terraform
        id: tfftpubip
        run: 
          echo "frontend_pub_ip=$(terraform output -raw frontend_public_ip)" >> $GITHUB_OUTPUT
         
      - name: Get Terraform Backend Private IP
        working-directory: terraform
        id: tfbkprip
        run: 
          echo "backend_pri_ip=$(terraform output -raw backend_private_ip)" >> $GITHUB_OUTPUT
  
      - name: Get Terraform Backend Instance ID
        working-directory: terraform
        id: tfbkinstid
        run: 
          echo "backend_inst_id=$(terraform output -raw backend_instance_id)" >> $GITHUB_OUTPUT
  
      - name: Get Terraform Frontend Instance ID
        working-directory: terraform
        id: tfftinstid
        run: 
          echo "frontend_inst_id=$(terraform output -raw frontend_instance_id)" >> $GITHUB_OUTPUT

      - name: Popoluate Ansible Inventory
        working-directory: terraform
        run: |
          cat <<EOF | sed 's/^          //' > ../ansible/inventory/testrunhost.yml
          all:
            vars:
              ansible_become: true
              ansible_become_method: sudo
              ansible_become_user: root
            children:
              backend:
                hosts:
                  ${{ steps.tfbkinstid.outputs.backend_inst_id }}:
                    ansible_connection: amazon.aws.aws_ssm
                    ansible_user: ubuntu
                    ansible_aws_ssm_region: us-east-1
                    ansible_aws_ssm_bucket_name: techbleat744
                    ansible_region: us-east-1
                    ansible_remote_tmp: /tmp/.ansible/tmp

              frontend:
                hosts:
                  ${{ steps.tfftinstid.outputs.frontend_inst_id }}:
                    ansible_connection: amazon.aws.aws_ssm
                    ansible_user: ubuntu
                    ansible_aws_ssm_region: us-east-1
                    ansible_aws_ssm_bucket_name: techbleat744
                    ansible_region: us-east-1
                    ansible_remote_tmp: /tmp/.ansible/tmp
          EOF
          cat ../ansible/inventory/testrunhost.yml

  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    permissions:
      id-token: write
      contents: read

    steps:
      # ----------------------------------
      # Checkout repo
      # ----------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
      # ----------------------------
      # Install Python 
      # ----------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Ansible and dependencies
        run: |
            python -m pip install --upgrade pip

      - name: Install Ansible and dependencies2
        run: |
            pip install ansible boto3 botocore 

      - name: Install amazon.aws collection
        run: |
            ansible-galaxy collection install amazon.aws

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: ${{ needs.terraform.outputs.role_arn }}
         aws-region: us-east-1
         
      - name: Run Ansible Playbook
        run: |
            ansible-playbook -i ansible/inventory/testrunhost.yml ansible/playbook.yml --extra-vars "backend_private_ip=${{ needs.terraform.outputs.backend_pri_ip }} frontend_public_ip=${{ needs.terraform.outputs.frontend_pub_ip }}" -vvvvv

                                                                                                             

         